### ISSUE TITLE
User Journey

### ISSUE THREAD

**Issue by AlaaEid-1** [GSG-CF05/Tasty-Online-Restaurant#24]
Readme File conisiste of:

**Comment by ahmedkhilla** [comment]
The user's journey in the site begins when he starts to search for our site on the internet and selects it from among all the available results.

If the user is new at first, he will go to the main section of the site, where he will find a welcome phrase and a simple description of the restaurant, and through it, he will be able to go to the main menu directly through our menu button available in it to display the basic classifications of the site, which are foods, sweets, and drinks, and specify what he wants from requests Based on the chosen classification, and then he will book the order and select the payment method through the Order Now button, Or go to the About Us section through the About Us button to learn about the nature of the restaurant and its services through the attached picture and the meals it offers through the attached description of the nature of the site’s work And its services, in addition to this, he will be able to access the main menu of the type of food he wants through the link available in it, and he will complete the rest of the steps of selecting the order and payment method as a normal user.

Whereas if an old user after finishes the main section, he will go to our special dishes section for this week to see the latest dishes and think about ordering them, or he will go to the main food menu directly through the link provided in the main menu in the upper section of the site without going to the special dishes section.

**Comment by ahmedkhilla** [comment]
The user's journey in the site begins when he starts to search for our site on the internet and selects it from among all the available results.

If the user is new at first, he will go to the main section of the site, where he will find a welcome phrase and a simple description of the restaurant, and through it, he will be able to go to the main menu directly through our menu button available in it to display the basic classifications of the site, which are foods, sweets, and drinks, and specify what he wants from requests Based on the chosen classification, and then he will book the order and select the payment method through the Order Now button, Or go to the About Us section through the About Us button to learn about the nature of the restaurant and its services through the attached picture and the meals it offers through the attached description of the nature of the site’s work And its services, in addition to this, he will be able to access the main menu of the type of food he wants through the link available in it, and he will complete the rest of the steps of selecting the order and payment method as a normal user.

Whereas if an old user after finishes the main section, he will go to our special dishes section for this week to see the latest dishes and think about ordering them, or he will go to the main food menu directly through the link provided in the main menu in the upper section of the site without going to the special dishes section.
